apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: e2e-basic-1777023980299
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-basic-1777023980299 
  name: e2e-basic-1777023980299
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: e2e-basic-1777023980299 
