apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: e2e-basic-1777023980299
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/quay_xjiang/test-image:github-0af19c984c45369b20e1d0c71a7f007b0844ecc2
        name: container-image  
